// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsdRwLtLPLtVn-9VaY4hd9zuFFlsdsWs0',
    appId: '1:861348967263:web:5629ad48b9e313cf11bcea',
    messagingSenderId: '861348967263',
    projectId: 'hajj-app-6ada1',
    authDomain: 'hajj-app-6ada1.firebaseapp.com',
    storageBucket: 'hajj-app-6ada1.appspot.com',
    measurementId: 'G-JPCCDRSS89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkL_wP_jJYv4FoavY8J2DeZq72-AkPS0U',
    appId: '1:861348967263:android:1153b5467521087a11bcea',
    messagingSenderId: '861348967263',
    projectId: 'hajj-app-6ada1',
    storageBucket: 'hajj-app-6ada1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ0mx5VZWrNPekzXmpUkYmrNaUbJTnQWw',
    appId: '1:861348967263:ios:81819ffc305f6d1a11bcea',
    messagingSenderId: '861348967263',
    projectId: 'hajj-app-6ada1',
    storageBucket: 'hajj-app-6ada1.appspot.com',
    iosBundleId: 'com.example.hajjApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ0mx5VZWrNPekzXmpUkYmrNaUbJTnQWw',
    appId: '1:861348967263:ios:94a8aae90e90ee4e11bcea',
    messagingSenderId: '861348967263',
    projectId: 'hajj-app-6ada1',
    storageBucket: 'hajj-app-6ada1.appspot.com',
    iosBundleId: 'com.example.hajjApp.RunnerTests',
  );
}
